# Workflow todo
name: Mon premier workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Listing files
        run: ls -al  
      - name: Setup PHP with pre-release PECL extension
        uses: shivammathur/setup-php@v2
          with:
               php-version: '8.2'
               extensions: xdebug-beta
        
        
